In [1]:
%pylab
%matplotlib inline

Using matplotlib backend: <object object at 0x110fa8b10>
Populating the interactive namespace from numpy and matplotlib


### Part 1

In [2]:
def parse_paths(fn):
    paths = []
    with open(fn) as data:
        for path in data.readlines():
            start,_,stop = path.split()
            paths += [[eval(start),eval(stop)]]
    return paths      

In [3]:
print(paths:=parse_paths('d5p1_test.txt'))

[[(0, 9), (5, 9)], [(8, 0), (0, 8)], [(9, 4), (3, 4)], [(2, 2), (2, 1)], [(7, 0), (7, 4)], [(6, 4), (2, 0)], [(0, 9), (2, 9)], [(3, 4), (1, 4)], [(0, 0), (8, 8)], [(5, 5), (8, 2)]]


In [4]:
def map_danger_1(paths):
    sz = np.array(paths).max()+1
    diagram = np.zeros([sz,sz],dtype='uint32')
    for path in paths:
        if path[0][0]==path[1][0] or path[0][1]==path[1][1]: # horizonta and vertical
            xrange = (min(path[0][0],path[1][0]),
                      max(path[0][0],path[1][0]))
            yrange = (min(path[0][1],path[1][1]),
                      max(path[0][1],path[1][1]))
            for i in range(xrange[0],xrange[1]+1):
                for j in range(yrange[0],yrange[1]+1):
                    diagram[j,i]+=1
    return diagram

In [5]:
diagram = map_danger_1(paths)
assert len(np.where(diagram>1)[0])==5

In [6]:
paths=parse_paths('d5p1.txt')
diagram = map_danger_1(paths)
print(f'The answer is {len(np.where(diagram>1)[0])}')

The answer is 5124


### Part 2

In [7]:
def map_danger_2(paths):
    sz = np.array(paths).max()+1
    diagram = np.zeros([sz,sz],dtype='uint32')
    for path in paths:
        xrange = (min(path[0][0],path[1][0]),
                  max(path[0][0],path[1][0]))
        yrange = (min(path[0][1],path[1][1]),
                  max(path[0][1],path[1][1]))
        if path[0][0]==path[1][0] or path[0][1]==path[1][1]: # horizonta and vertical
            xrange = (min(path[0][0],path[1][0]),
                      max(path[0][0],path[1][0]))
            yrange = (min(path[0][1],path[1][1]),
                      max(path[0][1],path[1][1]))
            for i in range(xrange[0],xrange[1]+1):
                for j in range(yrange[0],yrange[1]+1):
                    diagram[j,i]+=1
        elif abs(path[0][0]-path[1][0])==abs(path[0][1]-path[1][1]): # must be diagonal by design -- trust but verify
            xrange_ = np.arange(xrange[0],xrange[1]+1)
            if path[0][0]>path[1][0]:
                xrange_ = xrange_[::-1]
            yrange_ = np.arange(yrange[0],yrange[1]+1)
            if path[0][1]>path[1][1]:
                yrange_ = yrange_[::-1]
            for pos in zip(xrange_,yrange_):
                i,j=pos
                diagram[j,i]+=1
        else:
            print(f'Something is wrong with {path}')
    return diagram

In [8]:
paths=parse_paths('d5p1_test.txt')
diagram = map_danger_2(paths)
print(diagram)
assert len(np.where(diagram>1)[0])==12

[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]


In [9]:
paths=parse_paths('d5p1.txt')
diagram = map_danger_2(paths)
#print(diagram)
print(f'The answer is {len(np.where(diagram>1)[0])}')

The answer is 19771
