In [1]:
%pylab
%matplotlib inline

Using matplotlib backend: <object object at 0x10da65b10>
Populating the interactive namespace from numpy and matplotlib


### Part 1

In [2]:
def load_map(fn):
    octopus_map = []
    with open(fn) as data:
        for row in data:
            row = row.strip()
            octopus_map+=[[int(i) for i in row]]
    return octopus_map

In [3]:
fn = 'd11p1_test.txt'
octopus_map = np.array(load_map(fn))
display(octopus_map)

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [4]:
octopus_map = np.array(load_map(fn))
sz = np.shape(octopus_map)

for i in range(2):
    octopus_map=octopus_map+1
    display(octopus_map)

array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
       [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
       [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
       [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
       [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
       [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
       [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
       [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
       [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
       [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]])

array([[ 7,  6, 10,  5,  3,  6,  5,  4,  4,  5],
       [ 4,  9,  6,  7, 10,  7,  6,  9,  3,  3],
       [ 7,  4,  8,  6,  7,  7,  8,  3,  9,  5],
       [ 8,  3,  6,  3,  5,  5,  8,  3,  6,  8],
       [ 8,  5,  7,  9,  5, 10,  7,  6,  9, 10],
       [ 6,  3,  8,  9,  7,  4,  6,  8,  6,  7],
       [ 4,  3,  9,  8, 10,  6,  3,  9,  4,  3],
       [ 8, 10, 10,  4, 10, 10,  3,  3,  5,  6],
       [ 6, 10,  6,  8, 10,  6, 10,  7,  7,  6],
       [ 7,  4, 10,  5,  9,  7,  3,  7,  4,  8]])

In [5]:
ix = np.where(octopus_map==20)
print(ix)
len(ix[0])

(array([], dtype=int64), array([], dtype=int64))


0

In [16]:
def flash_octopi(fn,nsteps=100):
    octopus_map = np.array(load_map(fn))
    sz = np.shape(octopus_map)
    nflashes = 0
    for i in range(nsteps):
        hasflashed = np.zeros(np.shape(octopus_map))
        octopus_map=octopus_map+1
        while True:
            ix = np.where((octopus_map>=10) & (hasflashed==0))
            #print(ix)
            if not len(ix[0]):
                break
            for pos in zip(ix[0],ix[1]):
                nflashes+=1
                hasflashed[pos]=1
                octopus_map[max(pos[0]-1,0):min(pos[0]+2,sz[0]),
                            max(pos[1]-1,0):min(pos[1]+2,sz[1])]+=1
            if np.sum(hasflashed)==100:
                print(f'Synchronized at {i+1}')
        octopus_map[np.where(octopus_map>10)]=0
    #print(octopus_map)
    return(nflashes)

In [17]:
assert flash_octopi('d11p1_test.txt')==1656

In [18]:
print(f"The answer is {flash_octopi('d11p1.txt')}")

The answer is 1620


### Part 2

In [19]:
# Having just modified the function above to print when synchronized...
flash_octopi('d11p1_test.txt',nsteps=200) # test

Synchronized at 195


3125

In [21]:
flash_octopi('d11p1.txt',nsteps=400) # first printed response is the answer

Synchronized at 371
Synchronized at 381
Synchronized at 391


5904